name: Update View Counter

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-views:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Check and update views
        run: node update-views.js
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Pull latest changes first
          git pull origin main --rebase || true
          
          if git diff --quiet manga.json pending-views.json; then
            echo "✅ No changes to commit"
          else
            git add manga.json pending-views.json
            git commit -m "📊 Update view counter [skip ci]"
            
            # Retry push if failed
            max_retries=3
            count=0
            until git push origin main; do
              count=$((count+1))
              if [ $count -eq $max_retries ]; then
                echo "❌ Failed to push after $max_retries attempts"
                exit 1
              fi
              echo "⚠️  Push failed, retrying in 5 seconds... (attempt $count/$max_retries)"
              sleep 5
              git pull origin main --rebase
            done
            echo "✅ Views committed!"
          fi
